services:
  mongodb:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongoadmin
      MONGO_INITDB_DATABASE: django_mongodb_docker
    ports:
      - 27017:27017
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    command: 
      bash -c 'python manage.py makemigrations; python manage.py migrate; python manage.py runserver 0.0.0.0:8000'
    volumes:
      - .:/code
    ports:
      - 8000:8000
    links:
      - mongodb
